#!/bin/sh

if ! docker info >/dev/null 2>&1; then
    echo "ERROR: docker does not seem to be running, please run it and retry."
    exit 1
fi

COMMIT="$(git rev-parse --verify HEAD)"
BRANCH="$(git branch --show-current)"

docker build --build-arg COMMIT="$COMMIT" --build-arg BRANCH="$BRANCH" --tag backend .
yes | docker image prune
