#!/bin/sh

if ! docker info >/dev/null 2>&1; then
    echo "ERROR: docker does not seem to be running, please run it and retry."
    exit 1
fi

COMMIT_SHA="$(git rev-parse --verify HEAD)"
BRANCH_NAME="$(git branch --show-current)"

docker build --build-arg commit_sha="$COMMIT_SHA" --build-arg branch_name="$BRANCH_NAME" --tag backend .
yes | docker image prune
