#!/bin/sh

COMMIT="$(git rev-parse --verify HEAD)"
BRANCH="$(git branch --show-current)"

COMMIT="$COMMIT" BRANCH="$BRANCH" poetry run uvicorn app.main:app --host 0.0.0.0 --reload --log-level debug --env-file .env
