#!/bin/sh

COMMIT="$(git rev-parse --verify HEAD)"
BRANCH="$(git branch --show-current)"

COMMIT="$COMMIT" BRANCH="$BRANCH" env $(grep -v '^#' .env | xargs) poetry run pytest -sx --cov=app --cov-report=term-missing tests "$@"
